### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by comfytoday** [wpmark/wpbroadbean#18]
Hi, just doing some evaluation of this plugin for a site. Is there more documentation somewhere other than the single page wiki?
Looks good btw.
edit: futher to this, do you know of any working examples of wpbroadbean sites?
Thanks

**Comment by wpmark** [comment]
Documentation is on the to do list, just struggling for time at the moment. In terms of example feel free to get in touch and I can share some integration that I have done with the plugin.

http://markwilkinson.me/contact-me/
